/*
**  Copyright (c) 2011 Andrea Cisternino
**
**  This file is part of QtFractal.
**
**  QtFractal is free software: you can redistribute it and/or modify
**  it under the terms of the GNU General Public License as published
**  by the Free Software Foundation, version 2.
**
**  QtFractal is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License
**  along with QtFractal.  If not, see <http://www.gnu.org/licenses/>.
*/
/*!
 *  \file mainwindow.h
 *  \brief Application window definition
 *  \author Andrea Cisternino
 */

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "fractalwidget.h"
#include "ui_mainwindow.h"      // autogenerated

// ---- MainWindow -------------------------------------------------------

/*!
 *  \brief Application main window
 */
class MainWindow : public QMainWindow, private Ui::MainWindow
{
    Q_OBJECT

    FractalWidget fw;       //!< The Widget that will be the central area

public:

    // ---- Lifecycle ----------------------------------------------------

    /*!
     *  \brief Creates a MainWindow instance.
     */
    MainWindow(QWidget *parent = 0, Qt::WindowFlags flags = 0);

protected:

    // ---- Event listeners ----------------------------------------------

    /*!
     *  This is used to trap the ESC key and exit.
     */
    void keyReleaseEvent(QKeyEvent *event);

};

#endif  // MAINWINDOW_H
